sudo: false

env:
 - CABALVER=3.0 GHCVER=7.10.3
 - CABALVER=3.0 GHCVER=8.0.2
 - CABALVER=3.0 GHCVER=8.2.2
 - CABALVER=3.0 GHCVER=8.4.4
 - CABALVER=3.0 GHCVER=8.6.1
 - CABALVER=head GHCVER=head

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - ghc --version
 - cabal --version
 - travis_retry cabal update

install:
 - cabal install --dep

script:
 - cabal build

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.3
    - ghc-8.0.2
    - ghc-8.2.2
    - ghc-8.4.4
    - ghc-8.6.1
    - ghc-head
    - cabal-install-3.0
    - cabal-install-head
