sudo: false

env:
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1
 - CABALVER=head GHCVER=head

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - ghc --version
 - cabal --version
 - travis_retry cabal update

install:
 - cabal install --dep

script:
 - cabal build

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.6.3
    - ghc-7.8.4
    - ghc-7.10.3
    - ghc-8.0.1
    - ghc-head
    - cabal-install-1.18
    - cabal-install-1.22
    - cabal-install-1.24
    - cabal-install-head
